apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    # app.kubernetes.io/name: backend
    app: backend 
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
